sudo: false

language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

os:
  - linux

env:
  matrix:
    - CPU=8

script:
  - go test -v -cpu=$CPU -benchmem -bench=.

matrix:
  allow_failures:
    - go: tip
